# Generated by Django 4.2 on 2023-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=64)),
                ('power', models.IntegerField()),
                ('power_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attr_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
                ('luck', models.IntegerField()),
                ('cheese_effect', models.IntegerField()),
                ('title_req', models.IntegerField()),
                ('limited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=64)),
                ('power_type', models.CharField(max_length=64)),
                ('power', models.IntegerField()),
                ('power_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attr_bonus', models.DecimalField(decimal_places=2, max_digits=3)),
                ('luck', models.IntegerField()),
                ('cheese_effect', models.IntegerField()),
                ('title_req', models.IntegerField()),
                ('limited', models.BooleanField()),
            ],
        ),
    ]
